---
# This playbook handles notifications common to all nodes.

- name: restart the ntp daemon
  service: name=ntpd state=restarted

- name: restart the openssh daemon
  service: name=sshd state=restarted
