---
# This playbook contains common plays that will be run on all nodes.

- name: refresh the master package lists
  pacman: name=pacman state=installed update_cache=yes
  tags: pacman

- include: users.yml tags=users
- include: openssh.yml tags=ssh
- include: ntp.yml tags=ntp
